manual_keymap:
  controller:
    model: "8BitDo Ultimate"
    mode: "d_input"
    connection: "2.4ghz_dongle"
    device: "/dev/input/js0"
    name: "8BitDo 8BitDo Ultimate 2 Wireless Controller for PC"

  axes:
    left_stick:
      x:
        number: 0
        negative: "left"
        positive: "right"
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_min: -1.0
        normalized_center: 0.0
        normalized_max: 1.0
      y:
        number: 1
        negative: "up"
        positive: "down"
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_min: -1.0
        normalized_center: 0.0
        normalized_max: 1.0

    right_stick:
      x:
        number: 2
        negative: "left"
        positive: "right"
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_min: -1.0
        normalized_center: 0.0
        normalized_max: 1.0
      y:
        number: 3
        negative: "up"
        positive: "down"
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_min: -1.0
        normalized_center: 0.0
        normalized_max: 1.0

  dpad:
    left:
      type: "axis"
      number: 6
      pressed_value: -32767
      released_value: 0
      normalized_pressed: -1.0
      normalized_released: 0.0
    right:
      type: "axis"
      number: 6
      pressed_value: 32767
      released_value: 0
      normalized_pressed: 1.0
      normalized_released: 0.0
    up:
      type: "axis"
      number: 7
      pressed_value: -32767
      released_value: 0
      normalized_pressed: -1.0
      normalized_released: 0.0
    down:
      type: "axis"
      number: 7
      pressed_value: 32767
      released_value: 0
      normalized_pressed: 1.0
      normalized_released: 0.0

  buttons:
    a:
      number: 0
      pressed_value: 1
      released_value: 0
    b:
      number: 1
      pressed_value: 1
      released_value: 0
    x:
      number: 3
      pressed_value: 1
      released_value: 0
    y:
      number: 4
      pressed_value: 1
      released_value: 0

    minus:
      number: 10
      pressed_value: 1
      released_value: 0
    plus:
      number: 11
      pressed_value: 1
      released_value: 0
    select:
      number: 12
      pressed_value: 1
      released_value: 0

    lb:
      number: 6
      pressed_value: 1
      released_value: 0
    rb:
      number: 7
      pressed_value: 1
      released_value: 0
    l4:
      number: 16
      pressed_value: 1
      released_value: 0
    r4:
      number: 17
      pressed_value: 1
      released_value: 0
    pl:
      number: 5
      pressed_value: 1
      released_value: 0
    pr:
      number: 2
      pressed_value: 1
      released_value: 0

  triggers:
    lt:
      axis:
        number: 5
        released_value: -32767
        pressed_value: 32767
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_released: -1.0
        normalized_center: 0.0
        normalized_pressed: 1.0
      button:
        number: 8
        pressed_value: 1
        released_value: 0

    rt:
      axis:
        number: 4
        released_value: -32767
        pressed_value: 32767
        min_value: -32767
        center_value: 0
        max_value: 32767
        normalized_released: -1.0
        normalized_center: 0.0
        normalized_pressed: 1.0
      button:
        number: 9
        pressed_value: 1
        released_value: 0
