<?xml version="1.0"?>
<package format="3">
  <name>camera_driver</name>
  <version>0.2.0</version>
  <description>
    Low-latency OAK/DepthAI camera driver with on-device undistortion.
  </description>

  <maintainer email="ojeonghun@example.com">ojeonghun</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>depthai</depend>
  <depend>opencv4</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
