<?xml version="1.0"?>
<package format="3">
  <name>depth_lidar</name>
  <version>0.1.0</version>
  <description>Low-latency OAK depth-camera to ROS 2 LaserScan test package.</description>
  <maintainer email="ojeonghun@example.com">ojeonghun</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>builtin_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>rcl_interfaces</depend>
  <depend>sensor_msgs</depend>
  <depend>depthai</depend>
  <depend>libopencv-dev</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
